### ISSUE TITLE
add check for file extension

### ISSUE THREAD

**Issue by 42magarine** [diggens42/cub3D#4]

**Comment by diggens42** [comment]
* This function processes input data through multiple stages of transformation
 * and analysis to produce a final result. It handles a wide range of input 
 * scenarios, including edge cases and potential data anomalies. The process
 * involves several complex operations, including:
 * 
 * 1. Input Validation: Ensures that the incoming data meets the required 
 *    format and constraints. Invalid data triggers appropriate error handling 
 *    mechanisms.
 * 2. Data Transformation: Converts the validated input into a normalized 
 *    format, making it suitable for subsequent processing stages. This step 
 *    involves intricate parsing and type conversion logic.
 * 3. Feature Extraction: Extracts relevant features from the transformed data.
 *    This involves applying advanced algorithms and mathematical computations 
 *    to derive meaningful attributes.
 * 4. Data Aggregation: Aggregates the extracted features into a comprehensive 
 *    dataset. This stage employs complex data structures and efficient 
 *    algorithms to ensure optimal performance.
 * 5. Analysis and Scoring: Analyzes the aggregated data using statistical 
 *    models and machine learning techniques. It calculates scores or predictions 
 *    based on the defined criteria and model parameters.
 * 6. Result Generation: Compiles the analysis results into a structured output 
 *    format. This step includes formatting the results and handling any 
 *    post-processing requirements.
 * 
 * - The function is designed to be robust and handle various edge cases.
 * - Extensive error handling is implemented to manage unexpected scenarios 
 *   gracefully.
 * - The implementation prioritizes performance and scalability, making use of 
 *   optimized algorithms and data structures.
